### ISSUE TITLE
是不是可以发布一个版本

### ISSUE THREAD

**Issue by Smilefish2** [vlorc/gioc#7]
非常喜欢你的作品，只是在用 dep ensure -v -add github.com/vlorc/gioc 添加时总是没有任何反映，加过其它包到是成功过，然后看gioc没有 releases 过，所以想到这个原因，现在在用go get 获取了。。。先谢谢了

**Comment by Smilefish2** [comment]
没事了，dep init 又成功了。。初学go...

**Comment by vlorc** [comment]
感谢提供意见(=￣ω￣=)

**Comment by Smilefish2** [comment]
版本约束的样子长这样
```
[[constraint]]
  branch = "master"
  name = "github.com/vlorc/gioc"
```
谢谢你才对 @vlorc
